name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Starting the build stage
        run: echo "Starting the build stage..."

      - name: Say hello
        run: echo "Hello, ${{ github.actor }}! Building your project."

      - name: Create build artifact
        run: |
          mkdir -p build_artifacts
          echo "This is a build artifact." > build_artifacts/output.txt
          ls -R build_artifacts

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: my_build_artifact
          path: build_artifacts/

  test:
    name: Test Job
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: my_build_artifact

      - name: List downloaded files (debug)
        run: ls -R

      - name: Run tests
        run: |
          echo "Starting the test stage..."
          echo "Running tests..."
          cat build_artifacts/output.txt
          echo "Tests passed!"

  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    environment: production

    steps:
      - name: Starting deploy stage
        run: echo "Starting the deploy stage..."

      - name: Deploy to production
        run: |
          echo "Deploying to production environment: ${{ github.ref_name }}"
          echo "Deployment complete!"
